image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  repo: cursors
  domain: cursors.tedsummer.com
tasks:
- build: |
    tar -cvzf "site.tar.gz" -C ${repo} .
    hut pages publish -d ${domain} -p HTTPS site.tar.gz
